# # # input user 
# first_name = input('enter_first_name:')
# last_name = input('enter_last_name:')
# full_name = first_name +" "+ last_name 
# print(full_name)

# # # most important 
# # first_name = input() #input main message dyna lazmi ha (wrna searching hoti rahay gi)
# # last_name = input()  #input main message dyna lazmi ha 
# # full_name = first_name +" "+ last_name 
# # print(full_name)

# # marks = input('Enter your marks:')
# # total = input('Enter total marks')
# # percentage = (total / marks) * 100
# # percentage

# marks = float(input('Enter your marks:'))
# total = float(input('Enter total marks:'))
# percentage = (marks / total) * 100 
# print(percentage)

# num1 = input('Enter value1:')
# num2 = input('Enter value2:')
# s = num1+num2 #yahan addition nahi hogi.Concatenation hogi
# print(s)

# num1 = float(input('Enter value1:'))
# num2 = float(input('Enter value2:'))
# s = num1+num2 #yahan addition hogi
# print(s)

res = eval(input('Please provide expression to evaluate:'))
print(res)